# Generated by Django 2.2.17 on 2021-01-17 09:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_blogcomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComments',
            new_name='BlogComment',
        ),
    ]
