# Generated by Django 2.2.17 on 2021-01-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
    ]
